### ISSUE TITLE
FrontEnd: Sidebar

### ISSUE THREAD

**Issue by Bryandumpit** [FOR-TIMI/Starship#26]
Repurpose sidebar:
Dashboard as the Overview/Landing page
User to Friends
Product to Basket
Blog to Tavern
Login to Login/Logout

If user is not logged in clicking on: Friends, Baskets, and Tavern loads login/signup page.

**Comment by singhbawan** [comment]
The search option on top redirect to single symbol analytics page when searched for a symbol

**Comment by singhbawan** [comment]
On the single analytics page we will show the graph for that single symbol and an option to save that symbol to the basket

**Comment by Bryandumpit** [comment]
also check figma for page assignments: https://www.figma.com/file/21tkx8YyIjDWSJVLL1ySAh/Project-3?node-id=135%3A216&t=AMSUHq4fsldVJnu2-0
